### ISSUE TITLE
add use of condition named reference to gateway route condition field

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-ui#243]
we can now create named references for conditions (http://vamp.io/documentation/using-vamp/v0.9.2/conditions/)

It should be possible to use these in our condition UI field, ie: reference:my_conditionset  instead of the current ACL or shortcodes like Useragent = iPhone.

**Comment by dragoslav** [comment]
**Inline condition**
- deploy `sava:1.0` and then merge `sava:1.1` to it
- edit `sava/sava/webport` gateway - update the condition section for `sava:1.1` route:
```yaml
    condition:
      condition: user-agent is chrome
    condition_strength: 100%
```
- full gateway should be similar to: 
```yaml
name: sava/sava/webport
kind: gateway
metadata: {}
lookup_name: c69c9130565094947cd78805f9c2e3ec74186907
internal: true
proxy: sava/sava/webport
service:
  host: 192.168.99.100
  port: 40000/http
deployed: true
port: 40000/http
sticky: null
virtual_hosts:
- webport.sava.sava.vamp
routes:
  sava/sava/sava:1.1.0/webport:
    lookup_name: 2c3706a67b3956a7641d8be472a9b609591a4761
    weight: 0%
    balance: default
    condition:
      condition: user-agent is chrome
    condition_strength: 100%
    rewrites: []
    targets:
    - name: sava_sava-1-1-0-2e2fc6ab8a1cdbe79dc3.c4245253-e957-11e6-b29e-02421b3330a0
      host: 192.168.99.100
      port: 31125
      metadata: {}
  sava/sava/sava:1.0.0/webport:
    lookup_name: fef540f1c9e4eb21e045d935eac990d0d5d25825
    weight: 100%
    balance: default
    condition: null
    condition_strength: 0%
    rewrites: []
    targets:
    - name: sava_sava-1-0-0-6fd83b1fd01f7dd9eb7f.bca909d2-e957-11e6-b29e-02421b3330a0
      host: 192.168.99.100
      port: 31526
      metadata: {}
```
- check that `sava:1.1` is displayed in Chrome, `sava:1.0` in any other browser

This condition update can be achieved using gateway view page as well.

**Reference condition**

- deploy `sava:1.0` and `sava:1.1` like in previous example
- create a new condition:
```yaml
name: chrome
kind: condition
metadata: {}
condition: user-agent is chrome
```
- edit `sava/sava/webport` gateway - update the condition section for `sava:1.1` route:
```yaml
    condition:
      reference: chrome
    condition_strength: 100%
```
- check that `sava:1.1` is displayed in Chrome, `sava:1.0` in any other browser

Note: condition will be "expanded" after the update - reference is materialized from the available condition revision/snapshot and any further condition update won't be automatically applied in any deployment.
